name: Node Build Action
description: Setup Node, install dependencies and build the application

runs:
  using: composite

  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      shell: Build application
      run: npm install
