name: Node Build Action
description: Setup Node, install dependencies and build the application

inputs:
  node-version:
   required: true

runs:
  using: composite

  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - name: Install Dependencies
      shell: bash
      run: npm install
