name: NODE_PIPELINE

on:
  push

env:
  NODE_ENV: development-test
  API_KEY: ${{ secrets.API_KEY }}

jobs:
    Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm install

            # - name: Run Tests
            #   run: npm test

            - name: Check If Condition
              if: ${{ env.NODE_ENV == 'development' && github.event_name == 'push' }}
              run: echo "If condition satisfied"

            - name: Run Project
              run: echo "${{ github.event.sender.name }}"

            - name: Test success
              if: ${{ success() }}
              run: echo "All previous step executed properly"

            # - name: Intentional Test Failure
            #   run: npm test

            - name: Test failure
              if: ${{failure()}}
              run: echo "All previous job failed"

            - name: Run application
              run: node index.js

            - name: Test cancel workflow
              if: ${{cancelled()}}
              run: echo "Workflow cancelled"

            
              



            
