name: Common Workflow

on:
  workflow_call:
   inputs:
     message:
      required: true
      type: string

   secrets:
    APP_MESSAGE:
      required: true

jobs:
  common:
    runs-on: ubuntu-latest
    environment: production
 
    steps:
      - name: Test
        run: echo >> "Reusable workflow"
      
      - name: Log Inputs
        run: echo >> "My input message check ${{inputs.message}}"

      - name: Check secret
        run: |
          if [ -n "${{ secrets.APP_MESSAGE }}" ]; then
            echo "Secret is available"
          else
            echo "Secret is NOT available"
            exit 1
          fi
        