name: "ENVIRONMENT_PIPELINE"

on:
  workflow_run:
    workflows: ["NODE_PIPELINE"]
    types:
      - completed

jobs:
    TEST_ENVIRONMENT:

        runs-on: ubuntu-latest

        environment: production
        steps:
          - name: Check secret
            run: |
                if [ -n "${{ secrets.APP_MESSAGE }}" ]; then
                echo "Secret is available"
                else
                echo "Secret is NOT available"
                exit 1
                fi