name: "ENVIRONMENT_PIPELINE"

on:
  workflow_run:
    workflows: ["NODE_PIPELINE"]
    types:
      - completed

jobs:
    TEST_ENVIRONMENT:

        runs-on: ubuntu-latest

        environment: production
        steps:
          - name: Test Environment
            run: 'echo >> "${{secrets.APP_MESSAGE}}"'  