name: "MATRIX_PIPELINE"

on:
  workflow_run:
    workflows: ["NODE_PIPELINE"]
    types:
      - completed

jobs:

    Run:
     runs-on: ubuntu-latest

     strategy:
        matrix:
            node-versions: [18, 19, 20]

            exclude:
              - node-versions: 18
            
            include:
              - node-versions: 21
              - environment: "These is node 21 version"

     steps:

        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-versions}}

        - name: Echo Node Version
          run: 'echo "Environment: ${{ matrix.environment }}"'

        - name: Check Node Version
          run: node -v
        
    

