name: "PERMISSIONS_PIPELINE"

on:
  workflow_run:
    workflows: ["NODE_PIPELINE"]
    types:
      - completed

permissions: 
    # contents: read
    contents: write

jobs:
    
    RUN:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: Create file
              run: |
               echo "Written by GitHub Actions" > token-test.txt

            - name: Commit and push
              run: |
                git config user.name "harshnanekar"
                git config user.email "nanekarharshal2@gmail.com"

                git add token-test.txt
                git commit -m "Test GITHUB_TOKEN write permission"
                git push
            
            # - name: "Read Repository"
            #   run: |
            #     echo "Repository: ${{ github.repository }}"
            #     ls -la
