name: "SELF_HOSTED_PIPELINE"

on:
  workflow_run:
    workflows: ["NODE_PIPELINE"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/projects/"Node Pipeline"
          git pull origin main

      - name: Install dependencies
        run: |
          cd ~/projects/"Node Pipeline"
          npm ci

      - name: Restart application
        run: |
          pm2 restart node-pipeline